DROP TABLE IF EXISTS table_columns;
CREATE TABLE table_columns (
  id BIGINT NOT NULL UNIQUE,
  title varchar(255) NOT NULL UNIQUE,
  VERSION BIGINT NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS user_table;
CREATE TABLE user_table (
  id BIGINT NOT NULL UNIQUE,
  title varchar(255) NOT NULL UNIQUE,
  backlog BIGINT NOT NULL,
  next_do_do BIGINT NOT NULL,
  doing BIGINT NOT NULL,
  done BIGINT NOT NULL,
  VERSION BIGINT NOT NULL,
  PRIMARY KEY (id)
);
ALTER TABLE user_table ADD FOREIGN KEY (backlog) REFERENCES table_columns (id);
ALTER TABLE user_table ADD FOREIGN KEY (next_do_do) REFERENCES table_columns (id);
ALTER TABLE user_table ADD FOREIGN KEY (doing) REFERENCES table_columns (id);
ALTER TABLE user_table ADD FOREIGN KEY (done) REFERENCES table_columns (id);

DROP TABLE IF EXISTS TASKS;
CREATE TABLE TASKS (
  id BIGINT NOT NULL,
  VERSION BIGINT NOT NULL,
  TABLE_COLUMN BIGINT NOT NULL,
  name varchar(255) DEFAULT NULL,
  desc varchar(255) DEFAULT NULL,
  DUE_DATE DATE,
  PRIMARY KEY (id)
);

ALTER TABLE TASKS ADD FOREIGN KEY (TABLE_COLUMN) REFERENCES table_columns (id);

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
  id BIGINT NOT NULL UNIQUE,
  table_id BIGINT NOT NULL,
  first_name varchar(255) DEFAULT NULL,
  second_name varchar(255) DEFAULT NULL,
  nickname varchar(255) NOT NULL UNIQUE,
  VERSION BIGINT NOT NULL,
  PRIMARY KEY (id)
);
ALTER TABLE USERS ADD FOREIGN KEY (table_id) REFERENCES user_table (id);

DROP TABLE IF EXISTS LABELS;
CREATE TABLE LABELS (
  id BIGINT NOT NULL,
  VERSION BIGINT NOT NULL,
  colour varchar(255) DEFAULT NULL,
  description varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS TASK_LABELS;
create table TASK_LABELS (
    TASK_ID bigint not null,
    LABEL_ID bigint not null,
    PRIMARY KEY (TASK_ID, LABEL_ID)
);
ALTER TABLE TASK_LABELS ADD FOREIGN KEY (LABEL_ID) REFERENCES LABELS (id);
ALTER TABLE TASK_LABELS ADD FOREIGN KEY (TASK_ID) REFERENCES TASKS (id);

DROP sequence IF EXISTS USER_SEQUENCE;
DROP sequence IF EXISTS TASKS_SEQUENCE;
DROP sequence IF EXISTS LABEL_SEQUENCE;
DROP sequence IF EXISTS COLUMNS_SEQUENCE;
DROP sequence IF EXISTS TABLE_SEQUENCE;


create sequence USER_SEQUENCE start with 10000 increment by 1;
create sequence TASKS_SEQUENCE start with 10000 increment by 1;
create sequence LABEL_SEQUENCE start with 10000 increment by 1;
create sequence COLUMNS_SEQUENCE start with 10000 increment by 1;
create sequence TABLE_SEQUENCE start with 10000 increment by 1;
